In [91]:
import pandas as pd
import numpy as np

### Extraction of languages

In [92]:

train = pd.read_csv('raw/dslcc4/DSL-TRAIN.TXT', sep='\t', header=None)
test = pd.read_csv('raw/dslcc4/DSL-TEST-GOLD.TXT', sep='\t', header=None)
dev = pd.read_csv('raw/dslcc4/DSL-DEV.TXT', sep='\t', header=None)

sets = [train, test, dev]

In [93]:
test.head()

                                                   0      1
0  Sesaat setelah konser usai, Dira disambut sala...     id
1  Vous avez dit match amical ? Si les uns comme ...  fr-FR
2  «Il est malheureux que le gouvernement fédéral...  fr-CA
3  Una persona mayor es alguien que sabe más que ...  es-PE
4  Kali ini, ada perubahan positif pada kesihatan...     my

In [94]:
dev.head()

                                                   0   1
0  Ministar unutarnjih poslova Mohamed Ibrahim, k...  bs
1  Također, upriličen je i trilateralni sastanak ...  bs
2  Mnogi ljudi često jedu stvari koje ne vole da ...  bs
3  Nestabilno vrijeme s grmljavimom bilo je, kako...  bs
4  Amiqus - kompanija koja se bavi posredovanjem ...  bs

In [95]:
#Array of languages to keep
keep = ['es-ES', 'sr', 'hr', 'bs', 'es-PE', 'es-AR' , 'pt-PT', 'pt-BR']

for i in range(len(sets)):
    sets[i] = sets[i][sets[i][1].isin(keep)]

In [96]:
sets[0][sets[0][1].isin(['bs', 'hr', 'sr'])].to_csv('bks/bks_train.csv', index=False, header=False)
sets[1][sets[1][1].isin(['bs', 'hr', 'sr'])].to_csv('bks/bks_test.csv', index=False, header=False)
sets[2][sets[2][1].isin(['bs', 'hr', 'sr'])].to_csv('bks/bks_dev.csv', index=False, header=False)

sets[0][sets[0][1].isin(['es-ES', 'es-PE', 'es-AR'])].to_csv('es/es_train.csv', index=False, header=False)
sets[1][sets[1][1].isin(['es-ES', 'es-PE', 'es-AR'])].to_csv('es/es_test.csv', index=False, header=False)
sets[2][sets[2][1].isin(['es-ES', 'es-PE', 'es-AR'])].to_csv('es/es_dev.csv', index=False, header=False)

sets[0][sets[0][1].isin(['pt-PT', 'pt-BR'])].to_csv('pt/pt_train.csv', index=False, header=False)
sets[1][sets[1][1].isin(['pt-PT', 'pt-BR'])].to_csv('pt/pt_test.csv', index=False, header=False)
sets[2][sets[2][1].isin(['pt-PT', 'pt-BR'])].to_csv('pt/pt_dev.csv', index=False, header=False)